machine_descriptions = {
    "P1": """Dell Precision 3660 Tower là hệ thống máy tính bàn Workstation chuyên nghiệp với giá 31.900.000 VND. Máy được trang bị CPU Intel Core i7 thế hệ mới và 32GB RAM DDR5, mang lại khả năng xử lý đa nhiệm vượt trội, đáp ứng hoàn hảo cho các tác vụ Đồ họa kỹ thuật và Gaming cường độ cao khi kết hợp cùng card đồ họa rời RTX. Với thùng máy dạng Tower kích thước lớn, máy cung cấp hệ thống cổng kết nối I/O cực kỳ dồi dào ở cả mặt trước và mặt sau. Linh kiện đạt chuẩn Workstation cùng bộ nguồn (PSU) đạt chứng chỉ 80 Plus Platinum giúp máy vận hành với độ bền và sự ổn định cao trong môi trường làm việc 24/7. Đây là cỗ máy "tất cả trong một" cho người dùng cần sự tin cậy tuyệt đối từ văn phòng đến sáng tạo chuyên sâu.""",

    "P2": """PC ASUS B760 / i7-13700 là hệ thống máy tính bàn có hiệu năng mạnh mẽ với giá 16.900.000 VND. Máy được tối ưu hóa bằng cách kết hợp CPU Core i7 đa luồng và RAM 32GB tốc độ cao, lý tưởng cho Workstation chuyên nghiệp, Render đồ họa 3D và Gaming hiệu năng cao. Để giữ chi phí trong phạm vi G1, máy sử dụng Mainboard ASUS Prime B760 bền bỉ và Card đồ họa RTX series phổ thông. Cấu hình này linh hoạt đáp ứng mọi yêu cầu về kết nối I/O đa dạng với hệ thống cổng USB 3.2 và Type-C cùng độ bền linh kiện đạt chuẩn doanh nghiệp. Máy là lựa chọn hoàn hảo cho người dùng muốn hiệu năng CPU tối đa với ngân sách giới hạn nhưng vẫn đảm bảo khả năng nâng cấp lâu dài.""",

    "P3": """HP Z2 Tower G9 là biểu tượng của dòng máy trạm (Workstation) chuyên nghiệp với giá 39.500.000 VND. Với cấu hình mạnh mẽ gồm CPU Core i7-13700 và 32GB RAM DDR5, máy được thiết kế để xử lý các khối lượng công việc khổng lồ như Render phim 4K, mô phỏng 3D hay chạy các ứng dụng văn phòng phức tạp. Đặc điểm ăn tiền nhất của dòng Z2 là khả năng mở rộng không giới hạn với hệ thống cổng kết nối chuyên dụng và độ bền đạt chứng chỉ ISV, đảm bảo vận hành ổn định 24/7 mà không gặp lỗi hệ thống. Đây là lựa chọn hàng đầu cho các doanh nghiệp và chuyên gia đồ họa cần một chiếc PC HP "không thể bị đánh bại".""",

    "P4": """Acer Predator Orion 5000 là hệ thống PC tập trung vào sức mạnh xử lý thuần túy dành cho Game thủ chuyên nghiệp và người sáng tạo nội dung với giá 32.200.000 VND. Sử dụng nền tảng CPU Core i7 thế hệ 13/14 kết hợp cùng 32GB RAM, máy không chỉ cân tốt mọi tựa game AAA ở thiết lập cao nhất mà còn là một cỗ máy làm việc đồ họa đáng gờm. Với ngôn ngữ thiết kế case Predator hầm hố, máy cung cấp đầy đủ các cổng kết nối tốc độ cao ở phía trên và phía sau case. Hệ thống tản nhiệt IceFrost và linh kiện tuyển chọn giúp máy duy trì hiệu suất ổn định trong thời gian dài. Đối với fan của Acer, đây là mẫu PC mạnh mẽ nhất đáp ứng mọi yêu cầu khắt khe.""",

    "P5": """Dell OptiPlex 7010 Tower là giải pháp máy tính bàn đồng bộ tối ưu với giá 23.800.000 VND. Máy sử dụng CPU Intel Core i5 thế hệ 13 mới nhất cùng dung lượng RAM 32GB, mang lại sự cân bằng hoàn hảo giữa chi phí và hiệu năng cho các tác vụ Văn phòng nặng hoặc hỗ trợ các công việc Đồ họa và Gaming ở mức độ trung bình. Điểm mạnh nhất của dòng OptiPlex là độ bền chuẩn doanh nghiệp với khả năng hoạt động bền bỉ trong môi trường khắc nghiệt và hệ thống cổng kết nối I/O vô cùng phong phú từ cổng Serial, DisplayPort đến nhiều cổng USB tốc độ cao. Đây là sự lựa chọn "ăn chắc mặc bền" cho những ai cần cấu hình i5 mạnh mẽ nhất trong ngân sách tiết kiệm.""",

    "P6": """HP ProTower 400 G9 là dòng máy tính bàn "quốc dân" của HP, đáp ứng xuất sắc các tiêu chí cấu hình cao với mức giá 25.500.000 VND. Hệ thống được trang bị CPU Intel Core i5-13500 cực kỳ đa năng, kết hợp cùng 32GB RAM giúp xử lý mượt mà các file Excel hàng triệu dòng hoặc Render thiết kế 2D/3D nhẹ nhàng. Với khung máy chắc chắn đạt các chứng chỉ về độ bền và ổn định của HP cùng khả năng kết nối linh hoạt với nhiều thiết bị ngoại vi qua hệ thống cổng kết nối dồi dào, máy là trợ thủ đắc lực cho mọi nhu cầu sử dụng. Nếu bạn tìm kiếm một chiếc PC HP cấu hình i5 nhưng hiệu năng tiệm cận i7, đây chính là đáp án.""",
    
    "P7": """Đối với những người dùng yêu cầu khắt khe về thẩm mỹ và hiệu năng chuyên sâu của Asus với giá 49.900.000 VND, Asus ProArt Station PD5 là lựa chọn không thể bỏ qua. Máy được trang bị cấu hình "khủng" với CPU Core i7 và 32GB RAM, nhắm thẳng vào phân khúc Đồ họa chuyên nghiệp và Gaming đỉnh cao. Điểm đặc biệt của dòng ProArt là sự tối ưu hóa phần cứng để đạt độ ổn định tuyệt đối cho các phần mềm sáng tạo và hệ thống cổng I/O mặt trước cực kỳ tiện lợi cho việc kết nối thiết bị ngoại vi nhanh. Đây là cỗ máy đại diện cho sự kết hợp giữa nghệ thuật thiết kế và sức mạnh kỹ thuật.""",
    
    "P8": """Acer Aspire TC-1780 là hệ thống máy tính bàn có hiệu năng ổn định và linh hoạt với giá 27.850.000 VND của Acer. Máy được tối ưu hóa bằng cách kết hợp CPU Core i5-13400 và 16GB RAM, lý tưởng cho các tác vụ Văn phòng chuyên sâu, học tập và giải trí Gaming phổ thông. Để giữ chi phí tối ưu, máy sử dụng ổ cứng SSD 512GB tốc độ cao nhưng vẫn đảm bảo ngân sách A4. Thiết kế case dạng Tower truyền thống cung cấp khả năng kết nối I/O đa dạng với nhiều cổng USB ở mặt trước và sự ổn định cao nhờ hệ thống thoát nhiệt được cải tiến. Máy là lựa chọn hoàn hảo cho người dùng gia đình hoặc doanh nghiệp cần sự cân bằng giữa hiệu suất và giá thành.""",
    
    "P9":"""Asus ExpertCenter D5 là hệ thống máy tính bàn chuyên dụng cho doanh nghiệp có hiệu năng bền bỉ với giá 17.500.000 VND. Máy được tối ưu hóa bằng cách kết hợp CPU Core i5-12400 và 16GB RAM, lý tưởng cho môi trường Văn phòng hiện đại và các tác vụ tính toán đồ họa cơ bản. Với khung máy đạt tiêu chuẩn độ bền quân đội MIL-STD 810H, máy đảm bảo độ bền và sự ổn định vượt trội trong suốt thời gian dài sử dụng. Cấu hình này linh hoạt đáp ứng mọi yêu cầu về kết nối I/O đa dạng nhờ sở hữu đầy đủ các cổng kết nối từ truyền thống (VGA, PS/2) đến hiện đại (Type-C). Máy là lựa chọn hoàn hảo cho người dùng ưu tiên sự tin cậy và khả năng bảo mật dữ liệu của Asus.""",
    
    "P10": """Dell Vostro 3020 Tower là máy tính để bàn hướng đến nhu cầu văn phòng và văn phòng nâng cao, phù hợp cho doanh nghiệp nhỏ và người dùng cá nhân cần hệ thống ổn định với giá 21.500.000 VND. Máy được trang bị CPU Intel Core i5 hoặc i7, RAM từ 16GB đến 32GB, SSD dung lượng từ 512GB trở lên, đáp ứng tốt các tác vụ xử lý dữ liệu, làm việc đa nhiệm và các ứng dụng văn phòng chuyên sâu.Thiết kế thùng máy dạng Tower giúp hệ thống có nhiều cổng kết nối, thuận tiện cho việc mở rộng và kết nối các thiết bị ngoại vi. Linh kiện chính hãng Dell mang lại độ bền và độ ổn định cao, phù hợp cho môi trường làm việc liên tục.""",
    
    "P11": """HP Z4 G5 Workstation Tower là máy tính để bàn Workstation cao cấp, được thiết kế cho các nhu cầu đồ họa kỹ thuật, dựng hình 3D, render, và các tác vụ chuyên sâu yêu cầu hiệu năng mạnh và độ ổn định cao. Máy được trang bị CPU Intel Core i7, RAM từ 32GB trở lên, SSD dung lượng từ 512GB trở lên, hỗ trợ card đồ họa rời chuyên nghiệp. Thiết kế Tower kích thước lớn giúp hệ thống có nhiều cổng kết nối, khả năng mở rộng linh hoạt và tản nhiệt hiệu quả. Linh kiện đạt chuẩn Workstation cho phép máy vận hành ổn định liên tục trong thời gian dài, phù hợp với môi trường làm việc chuyên nghiệp. Mức giá của HP Z4 G5  trên thị trường là 65.900.000 VND, phù hợp với nhóm người dùng cao cấp.""",
    
    "P12": """Acer Veriton M6700G Tower là máy tính để bàn dành cho doanh nghiệp và văn phòng, hướng đến sự ổn định, bền bỉ và khả năng mở rộng linh hoạt. Máy hỗ trợ CPU Intel Core i5 hoặc i7, RAM từ 16GB đến 32GB, SSD dung lượng từ 256GB đến 512GB, đáp ứng tốt các tác vụ văn phòng nâng cao và xử lý dữ liệu.Thiết kế thùng máy dạng Tower cung cấp nhiều cổng kết nối, thuận tiện cho việc sử dụng nhiều thiết bị ngoại vi. Với linh kiện đạt chuẩn doanh nghiệp, Acer Veriton M6700G phù hợp cho môi trường làm việc liên tục. Mức giá trên thị trường 27.900.000 VND, phù hợp với phân khúc văn phòng tầm trung. """,
    
    "P13": """Asus ExpertCenter D7 Tower (D700SD) là máy tính để bàn mạnh mẽ dành cho doanh nghiệp, được thiết kế để cân bằng tối ưu giữa hiệu năng xử lý và ngân sách đầu tư. Máy hỗ trợ đa dạng cấu hình với CPU Intel Core i5 hoặc i7 thế hệ mới, dung lượng RAM linh hoạt từ 16GB đến 32GB và SSD từ 256GB đến 512GB, đáp ứng tốt từ các công việc văn phòng phức tạp đến xử lý đồ họa chuyên sâu và đa nhiệm. Với thiết kế thùng máy dạng Tower bền bỉ đạt chuẩn quân đội MIL-STD-810H, máy cung cấp hệ thống tản nhiệt tiên tiến và đầy đủ các cổng kết nối ngoại vi giúp tối ưu hóa hiệu suất làm việc. Asus ExpertCenter D7 là lựa chọn lý tưởng cho các tổ chức yêu cầu sự ổn định lâu dài và khả năng nâng cấp dễ dàng. Mức giá trên thị trường dao động từ 18.500.000 VND đến 32.000.000 VND, phù hợp cho cả phân khúc giá rẻ  và cao cấp tùy vào cấu hình lựa chọn.""",
    
    "P14": """HP EliteTower 800 G9 là máy tính để bàn doanh nghiệp cao cấp, được thiết kế để mang lại hiệu năng tối ưu và khả năng bảo mật mạnh mẽ. Máy hỗ trợ cấu hình đa dạng với CPU Intel Core i5 hoặc i7, bộ nhớ RAM từ 16GB đến 32GB, cùng ổ cứng SSD dung lượng từ 256GB đến 512GB, đáp ứng hoàn hảo các tác vụ văn phòng phức tạp, xử lý dữ liệu lớn và đồ họa chuyên dụng. Thiết kế thùng máy dạng Tower hiện đại cung cấp khả năng nâng cấp linh hoạt và hệ thống cổng kết nối phong phú, thuận tiện cho việc kết nối nhiều thiết bị ngoại vi. Với linh kiện đạt tiêu chuẩn độ bền cao và tính năng bảo mật HP Wolf Security, máy phù hợp cho môi trường làm việc chuyên nghiệp đòi hỏi tính ổn định tuyệt đối. Mức giá trên thị trường 35.500.000 VND, phù hợp với phân khúc cao cấp.""",
    
    "P15": """Acer Veriton M4690G là dòng máy tính để bàn mạnh mẽ dành cho doanh nghiệp và đồ họa, hướng đến sự ổn định và khả năng xử lý vượt trội. Máy hỗ trợ cấu hình CPU Intel Core i5 hoặc i7 thế hệ mới, dung lượng RAM từ 16GB đến 32GB, đi kèm SSD từ 256GB đến 512GB, giúp vận hành mượt mà các ứng dụng thiết kế và tính toán nặng. Thiết kế thùng máy Tower lớn cung cấp không gian rộng rãi cho việc nâng cấp phần cứng và tích hợp đầy đủ các cổng giao tiếp hiện đại. Với linh kiện đạt chuẩn doanh nghiệp và hệ thống bảo mật TPM 2.0, Acer Veriton M4690G là giải pháp tin cậy cho môi trường làm việc cường độ cao. Mức giá trên thị trường khoảng 23.500.000 VND, phù hợp với phân khúc văn phòng giá rẻ và tầm trung.""",

    "P16": """Acer Nitro 50 (N50-650) là máy tính để bàn chuyên game mạnh mẽ, hướng đến hiệu năng xử lý đồ họa mượt mà, tốc độ cao và trải nghiệm giải trí tối ưu. Máy hỗ trợ cấu hình CPU Intel Core i5 hoặc i7, RAM từ 16GB đến 32GB, SSD dung lượng từ 256GB đến 512GB, đáp ứng tốt các tựa game AAA và các tác vụ đa nhiệm cường độ cao. Thiết kế thùng máy dạng Tower với dải đèn LED đỏ đặc trưng cung cấp đầy đủ các cổng kết nối hiện đại, thuận tiện cho việc kết nối linh hoạt các thiết bị ngoại vi gaming. Với hệ thống tản nhiệt tiên tiến và linh kiện đạt chuẩn chất lượng, Acer Nitro 50 phù hợp cho môi trường sử dụng liên tục. Mức giá trên thị trường 25.500.000 VND, phù hợp với phân khúc gaming tầm trung.""",

    "P17": """Acer ConceptD 300 là máy tính để bàn chuyên dụng dành cho các nhà thiết kế và sáng tạo nội dung, hướng đến sự yên tĩnh, độ chính xác cao và hiệu suất đồ họa vượt trội. Máy hỗ trợ cấu hình CPU Intel Core i5 hoặc i7, RAM từ 16GB đến 32GB, SSD dung lượng từ 256GB đến 512GB, đáp ứng tốt các phần mềm thiết kế 2D, 3D và dựng phim chuyên nghiệp. Thiết kế thùng máy dạng Tower màu trắng thanh lịch với mặt lưới vân gỗ cung cấp nhiều cổng kết nối tốc độ cao, thuận tiện cho việc truyền tải dữ liệu hình ảnh và video lớn. Với linh kiện đạt chuẩn chuyên gia và khả năng vận hành êm ái, Acer ConceptD 300 phù hợp cho môi trường làm việc sáng tạo. Mức giá trên thị trường 38.900.000 VND, phù hợp với phân khúc đồ họa cao cấp.""",

    "P18": """Dell OptiPlex Small Form Factor (7010/Plus) là dòng máy tính để bàn doanh nghiệp cao cấp, nổi tiếng với sự bền bỉ và khả năng bảo mật hàng đầu. Máy hỗ trợ cấu hình mạnh mẽ với CPU Intel Core i5 hoặc i7 thế hệ mới, bộ nhớ RAM từ 16GB đến 32GB, cùng ổ cứng SSD từ 256GB đến 512GB, đảm bảo xử lý mượt mà mọi tác vụ quản lý và đa nhiệm phức tạp. Thiết kế nhỏ gọn (SFF) giúp tiết kiệm không gian làm việc tối đa nhưng vẫn cung cấp đầy đủ các cổng kết nối hiện đại và khả năng quản lý từ xa thông qua công nghệ Intel vPro. Với linh kiện đạt tiêu chuẩn độ bền quân đội và hệ thống tản nhiệt tối ưu, đây là lựa chọn số một cho các tập đoàn và môi trường làm việc chuyên nghiệp. Mức giá trên thị trường 34.500.000 VND, phù hợp với phân khúc cao cấp.""",

    "P19": """Dell Inspiron Desktop (3020 MT) là mẫu máy tính để bàn đa năng, được thiết kế để cân bằng giữa nhu cầu làm việc đồ họa cơ bản và giải trí gia đình. Máy trang bị CPU Intel Core i5 hoặc i7, RAM linh hoạt từ 16GB đến 32GB, cùng SSD dung lượng 256GB đến 512GB, hỗ trợ tốt các phần mềm thiết kế 2D và các tựa game phổ thông. Thiết kế thùng máy Tower truyền thống cho phép lưu thông không khí tốt và dễ dàng nâng cấp thêm card đồ họa rời hoặc dung lượng lưu trữ trong tương lai. Với độ tin cậy đặc trưng của dòng Inspiron và mức giá cạnh tranh, sản phẩm này đáp ứng tốt nhu cầu của người dùng phổ thông cần hiệu năng ổn định. Mức giá trên thị trường 21.900.000 VND, phù hợp với phân khúc giá rẻ/tầm trung.""",

    "P20": """Asus ExpertCenter D7 SFF (D700SD) là máy tính để bàn có thiết kế nhỏ gọn chuyên dụng cho doanh nghiệp, đề cao tính bền bỉ và hiệu suất làm việc chuyên nghiệp. Máy hỗ trợ cấu hình CPU Intel Core i5 hoặc i7, bộ nhớ RAM linh hoạt từ 16GB đến 32GB, cùng ổ cứng SSD từ 256GB đến 512GB, giúp vận hành mượt mà các phần mềm quản lý và tác vụ đa nhiệm. Với thiết kế đạt chuẩn quân đội Mỹ MIL-STD-810H và hệ thống tản nhiệt tối ưu, máy đảm bảo hoạt động ổn định trong thời gian dài. Thân máy nhỏ gọn giúp tiết kiệm diện tích nhưng vẫn trang bị đầy đủ các cổng kết nối cần thiết cho công việc văn phòng hiện đại. Mức giá trên thị trường 18.500.000 VND, rất phù hợp cho phân khúc giá rẻ.""",

    "P21": """HP Pro SFF 400 G9 là phiên bản máy tính để bàn dạng nhỏ gọn (Small Form Factor), được thiết kế tối ưu cho không gian văn phòng hiện đại nhưng vẫn duy trì hiệu suất mạnh mẽ. Máy hỗ trợ cấu hình linh hoạt với CPU Intel Core i5 hoặc i7, bộ nhớ RAM từ 16GB đến 32GB và ổ cứng SSD từ 256GB đến 512GB, giúp xử lý nhanh chóng các tác vụ kế toán, quản lý dữ liệu và phần mềm doanh nghiệp chuyên dụng. Với các tính năng bảo mật tiên tiến của HP và khả năng hoạt động bền bỉ, thiết bị này đảm bảo tính ổn định cao cho người dùng chuyên nghiệp. Thiết kế thông minh cho phép nâng cấp linh kiện dễ dàng và tích hợp đầy đủ các cổng kết nối cần thiết. Mức giá trên thị trường khoảng 22.500.000 VND, phù hợp với phân khúc giá rẻ/tầm trung.""",

    "P22": """HP Victus 15L là dòng máy tính để bàn chuyên dụng cho Gaming và thiết kế đồ họa, mang lại sự cân bằng hoàn hảo giữa hiệu suất mạnh mẽ và thiết kế hiện đại. Máy hỗ trợ cấu hình CPU Intel Core i7, bộ nhớ RAM tối đa 32GB và ổ cứng SSD lên đến 512GB, giúp xử lý mượt mà các tựa game AAA cũng như các phần mềm đồ họa chuyên sâu như Adobe Premiere, AutoCAD hay 3ds Max. Thùng máy có thiết kế tinh tế với logo Victus nổi bật và hệ thống đèn LED tùy chỉnh, cùng khả năng nâng cấp linh hoạt card đồ họa rời. Với hệ thống tản nhiệt tiên tiến, HP Victus 15L đảm bảo hiệu năng ổn định trong suốt quá trình sử dụng cường độ cao. Mức giá trên thị trường khoảng 32.500.000 VND, hoàn toàn phù hợp với phân khúc cao cấp.""",

    "P23": """Acer Veriton S6690G là dòng máy tính đồng bộ cao cấp nhất trong hệ sinh thái Veriton, được thiết kế cho các tập đoàn và doanh nghiệp đòi hỏi tính ổn định và hiệu suất vượt trội. Máy trang bị CPU Intel Core i7, bộ nhớ RAM tối đa 32GB, và ổ cứng SSD 512GB. Với khả năng bảo mật cấp độ phần cứng (TPM 2.0), thiết kế vỏ máy cứng cáp đạt chuẩn bền bỉ và hệ thống tản nhiệt chuyên nghiệp, máy dễ dàng xử lý các tác vụ văn phòng phức tạp hoặc đồ họa kỹ thuật. Thiết bị cung cấp sự linh hoạt tối đa với nhiều khe cắm mở rộng và cổng kết nối tốc độ cao. Mức giá trên thị trường khoảng 31.500.000 VND, thuộc phân khúc cao cấp.""",
    
    "P24": """Dell XPS 8960 là dòng máy tính để bàn cao cấp bậc nhất của Dell, được thiết kế để mang lại hiệu năng tối thượng trong một diện mạo sang trọng và tinh tế. Máy sở hữu cấu hình mạnh mẽ với CPU Intel Core i7, bộ nhớ RAM 32GB và ổ cứng SSD 512GB, đáp ứng hoàn hảo cho các nhà sáng tạo nội dung chuyên nghiệp, biên tập video 4K và game thủ hạng nặng. Với hệ thống tản nhiệt chất lượng cao và khả năng vận hành cực kỳ yên tĩnh, XPS 8960 đảm bảo duy trì hiệu suất đỉnh cao trong thời gian dài. Thiết kế thùng máy hiện đại với các cổng kết nối tốc độ cao ở mặt trước giúp tối ưu hóa sự tiện lợi cho người dùng. Mức giá trên thị trường khoảng 45.500.000 VND, đại diện tiêu biểu cho phân khúc cao cấp."""
}